### ISSUE TITLE
Let CosmosSchema reconstitute "tables" using the cosmos metadata Accumulo table

### ISSUE THREAD

**Issue by joshelser** [joshelser/cosmos#5]
CosmosSchema only knows about "tables" that were created and had items loaded into them.

If we have a permanent Accumulo instance up and running, we need to recreate the table mapping so that we can ingest once and query many times.

**Comment by joshelser** [comment]
It would probably be best to add a method on SortingMetadata which can scan the appropriate metadata table for cosmos (metacosmos by default) and then get back a list of SortableResults

**Comment by joshelser** [comment]
Oh ho. I see @phrocker started to stub out this logic in CosmosImpl#fetch :D

**Comment by joshelser** [comment]
Did a bunch of work here in regards to this notion. Renamed the SortableResult into a Store to better describe the "container" idea behind the class.

Added a PersistedStores class which can encapsulate all of the Store classes for a Cosmos instance.

This doesn't really address the import/export of the data of a Store; it's more for persisting and recreating a Store object given what's currently in the Cosmos instance

**Comment by phrocker** [comment]
Added some base functionality for show tables that includes pulling all persisted stores. Wondering if we should store a time stamp for future age off I don't recall the ts being populated

**Comment by joshelser** [comment]
> Wondering if we should store a time stamp for future age off I don't recall the ts being populated

I believe I did anything with the timestamp (anywhere), but I agree completely.

I can see this boiling down into two basic use cases
1. Space management. Administration level, remove data after it's at least such and such an age.
2. Long-running Stores in which new data is added and old data can roll off. (user managed)

One is easy and two is slightly harder yet not unmanageable. Could use HDFS or ZK as a store to read state from to load some age rules. I'm not sure how much I like that though. Perhaps something could be added when (re-)serializing a store, to update that TTL info wherever it's stored?

Ultimately, it would be super-boss to be able to have this info stored in Accumulo, cache it, and then auto-preload into the IteratorEnvironment when making a ScanSession, MulitScanSession, or compaction. Thoughts?
